name: CI/CD pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask
          pip install -r requirements.txt
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=src" >> $GITHUB_ENV
      - name: Set MONGODBURI
        run: echo "MONGODBURI=${{ secrets.MONGODBURI }}" >> $GITHUB_ENV
      - name: Print environment variable for debugging
        run: |
          echo "MONGODBURI is set."
          # For debugging purposes, use a placeholder or substring of the secret to avoid exposing the full secret
          echo "MONGODBURI starts with: ${MONGODBURI:0:10}..."
        env:
          MONGODBURI: ${{ secrets.MONGODBURI }}
      - name: Run tests
        run: |
          python -m unittest discover -s src/tests/unit/ -p "*.py"
        env:
          PYTHONPATH: ${{ env.PYTHONPATH }}
          MONGODBURI: ${{ secrets.MONGODBURI }}